export const SWITCH_ROWS = 'SWITCH_ROWS';
export const SET_IS_EDITING = 'SET_IS_EDITING';
export const SET_EDITING_ROW_ACTION_NAME = 'SET_EDITING_ROW_ACTION_NAME';
export const SET_EDITING_ROW_ACTION_TARGET_SECTION =
  'SET_EDITING_ROW_ACTION_TARGET_SECTION';
export const SET_EDITING_ROW_ACTION_POINTS = 'SET_EDITING_ROW_ACTION_POINTS';
export const SET_EDITING_ROW_ACTION_DATE_JOINED_WAITING_LIST =
  'SET_EDITING_ROW_ACTION_DATE_JOINED_WAITING_LIST';
export const ADD_NEW_ROW = 'ADD_NEW_ROW';
