const SWITCH_ROWS = 'SWITCH_ROWS';
const SET_IS_EDITING = 'SET_IS_EDITING';
const SET_EDITING_ROW_ACTION_NAME = 'SET_EDITING_ROW_ACTION_NAME';
const SET_EDITING_ROW_ACTION_TARGET_SECTION =
  'SET_EDITING_ROW_ACTION_TARGET_SECTION';
const SET_EDITING_ROW_ACTION_POINTS = 'SET_EDITING_ROW_ACTION_POINTS';
const SET_EDITING_ROW_ACTION_DATE_JOINED_WAITING_LIST =
  'SET_EDITING_ROW_ACTION_DATE_JOINED_WAITING_LIST';
const ADD_NEW_ROW = 'ADD_NEW_ROW';
