export const CLEAR_ADDING_ROW = 'CLEAR_ADDING_ROW';
export const SET_ADDING_ROW_ACTION_NAME = 'SET_ADDING_ROW_ACTION_NAME';
export const SET_ADDING_ROW_ACTION_TARGET_SECTION =
  'SET_ADDING_ROW_ACTION_TARGET_SECTION';
export const SET_ADDING_ROW_ACTION_POINTS = 'SET_ADDING_ROW_ACTION_POINTS';
export const SET_ADDING_ROW_ACTION_DATE_JOINED_WAITING_LIST =
  'SET_ADDING_ROW_ACTION_DATE_JOINED_WAITING_LIST';
